connector.name=delta_lake
hive.metastore=file
hive.metastore.catalog.dir=s3://lakehouse-data/
hive.s3.endpoint=http://minio:9000
hive.s3.aws-access-key=lakehouse
hive.s3.aws-secret-key=lakehouse123
hive.s3.path-style-access=true
delta.enable-non-concurrent-writes=true
